---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:4.2.18
        name: mongodb
