---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  labels:
    app: mongodb   
spec:
  type: ClusterIP
  ports:
   - name: mongodb
     protocol: TCP
     port: 27017
     targetPort: 27017
  selector:
    app: mongodb

