---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  rules:
  - host: '{{ .Values.Domain_Name | default (printf "stage.yar2.space" ) }}'
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
          servicePort: {{ .Values.service.externalPort }}
