---
service:
  internalPort: 8000
  externalPort: 8000

image:
  repository: yar2dev/crawler
  tag: latest

#databaseHost:
#databasePort:
#RabbitmqHost:
#RabbitmqQueue:
#RabbitmqUsername:
#RabbitmqPassword:
#CheckInterval:
#ExcludeURLS: