---
kind: Service
apiVersion: v1
metadata:
  name: zipkin
  labels:
    app: zipkin

    
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 9411
     targetPort: 9411
  selector:
    run: zipkin